using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "deny", network = (allow = [])),
    (name = "application",
     worker = (
       compatibilityDate = "2026-07-27",
       globalOutbound = "deny",
       modules = [
         (name = "worker.mjs", esModule = embed "worker.mjs"),
         (name = "provider-capability.mjs", esModule = embed "provider-capability.mjs"),
         (name = "provider-object-store.mjs", esModule = embed "provider-object-store.mjs"),
         (name = "provider-identity.mjs", esModule = embed "provider-identity.mjs"),
         (name = "provider-hash.mjs", esModule = embed "provider-hash.mjs"),
         (name = "provider-http.mjs", esModule = embed "provider-http.mjs"),
         (name = "provider-log.mjs", esModule = embed "provider-log.mjs"),
         (name = "get/component.js", esModule = embed "get/component.js"),
         (name = "get/component.core.wasm", wasm = embed "get/component.core.wasm"),
         (name = "get/component.core2.wasm", wasm = embed "get/component.core2.wasm"),
         (name = "get/component.core3.wasm", wasm = embed "get/component.core3.wasm"),
         (name = "get/component.core4.wasm", wasm = embed "get/component.core4.wasm"),
         (name = "put/component.js", esModule = embed "put/component.js"),
         (name = "put/component.core.wasm", wasm = embed "put/component.core.wasm"),
         (name = "put/component.core2.wasm", wasm = embed "put/component.core2.wasm"),
         (name = "put/component.core3.wasm", wasm = embed "put/component.core3.wasm"),
         (name = "put/component.core4.wasm", wasm = embed "put/component.core4.wasm"),
         (name = "cas/component.js", esModule = embed "cas/component.js"),
         (name = "cas/component.core.wasm", wasm = embed "cas/component.core.wasm"),
         (name = "cas/component.core2.wasm", wasm = embed "cas/component.core2.wasm"),
         (name = "cas/component.core3.wasm", wasm = embed "cas/component.core3.wasm"),
         (name = "cas/component.core4.wasm", wasm = embed "cas/component.core4.wasm"),
         (name = "sign/component.js", esModule = embed "sign/component.js"),
         (name = "sign/component.core.wasm", wasm = embed "sign/component.core.wasm"),
         (name = "sign/component.core2.wasm", wasm = embed "sign/component.core2.wasm"),
         (name = "sign/component.core3.wasm", wasm = embed "sign/component.core3.wasm"),
         (name = "sign/component.core4.wasm", wasm = embed "sign/component.core4.wasm"),
         (name = "verify/component.js", esModule = embed "verify/component.js"),
         (name = "verify/component.core.wasm", wasm = embed "verify/component.core.wasm"),
         (name = "verify/component.core2.wasm", wasm = embed "verify/component.core2.wasm"),
         (name = "verify/component.core3.wasm", wasm = embed "verify/component.core3.wasm"),
         (name = "verify/component.core4.wasm", wasm = embed "verify/component.core4.wasm"),
         (name = "hash/component.js", esModule = embed "hash/component.js"),
         (name = "hash/component.core.wasm", wasm = embed "hash/component.core.wasm"),
         (name = "hash/component.core2.wasm", wasm = embed "hash/component.core2.wasm"),
         (name = "hash/component.core3.wasm", wasm = embed "hash/component.core3.wasm"),
         (name = "hash/component.core4.wasm", wasm = embed "hash/component.core4.wasm"),
         (name = "http-post/component.js", esModule = embed "http-post/component.js"),
         (name = "http-post/component.core.wasm", wasm = embed "http-post/component.core.wasm"),
         (name = "http-post/component.core2.wasm", wasm = embed "http-post/component.core2.wasm"),
         (name = "http-post/component.core3.wasm", wasm = embed "http-post/component.core3.wasm"),
         (name = "http-post/component.core4.wasm", wasm = embed "http-post/component.core4.wasm"),
         (name = "log-read/component.js", esModule = embed "log-read/component.js"),
         (name = "log-read/component.core.wasm", wasm = embed "log-read/component.core.wasm"),
         (name = "log-read/component.core2.wasm", wasm = embed "log-read/component.core2.wasm"),
         (name = "log-read/component.core3.wasm", wasm = embed "log-read/component.core3.wasm"),
         (name = "log-read/component.core4.wasm", wasm = embed "log-read/component.core4.wasm"),
       ],
     )),
  ],
  sockets = [
    (name = "http", address = "127.0.0.1:4176", http = (), service = "application"),
  ],
);
